class AppError(Exception): ...


class DomainError(AppError): ...


class ValidationError(DomainError): ...


class NotFoundError(DomainError): ...


class DuplicateError(DomainError): ...


class OperationError(DomainError): ...


class PersistenceError(AppError): ...


class StorageLoadError(PersistenceError): ...


class StorageSaveError(PersistenceError): ...
